#!/bin/bash -ex


dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f -O $PROXY $1; cd -
}
VERSION="3.2.4"
URL="https://www.phpbb.com/files/release/phpBB-${VERSION}.zip"

dl $URL /usr/local/src
