#!/bin/bash -e
# regenerate phpbb mysql password

. /etc/default/inithooks

PASSWORD=$(mcookie)

CONF=/var/www/phpBB/config.php
sed -i "s/\$dbpasswd = \(.*\)/\$dbpasswd = \'$PASSWORD\';/" $CONF

$INITHOOKS_PATH/bin/mysqlconf.py --user=phpbb --pass="$PASSWORD"

