#!/bin/bash -e
# regenerate phpbb mysql password

. /etc/default/inithooks

PASSWORD=$(mcookie)

CONF=/etc/phpbb3/database.inc.php
sed -i "s/\$dbpass=\(.*\)/\$dbpass=\'$PASSWORD\';/" $CONF

CONF=/etc/dbconfig-common/phpbb3.conf
sed -i "s/dbc_dbpass=\(.*\)/dbc_dbpass=\'$PASSWORD\'/" $CONF

$INITHOOKS_PATH/bin/mysqlconf.py --user=phpbb3 --pass="$PASSWORD"

